name: Java CI with Gradle

on: [pull_request, push]

concurrency:
  group: "latest"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@v4.6.0
        with:
          java-version: '21'
          distribution: 'zulu'
          java-package: 'jdk'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Fetch Build Time
        run: echo "time=$(date +%Y-%m-%d)" >> $env:GITHUB_ENV

      - name: Build
        run: ./gradlew build

      - name: Remove *-sources.jar
        run: rm ./build/libs/*-sources.jar || true

      - uses: "0xDylan/action-auto-releases-n20@v1.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: nightly-${{env.time}}
          prerelease: true
          title: Nightly Build ${{env.time}}
          files: |
            ./build/libs/*.jar
